apiVersion: v1
kind: Service
metadata:
  name: cards-db
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
  type: ClusterIP
  selector:
    app: cards-postgres