# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: accounts-deployment
serviceName: accounts
appLabel: accounts
appName: accounts

replicaCount: 1

image:
  repository: siya7/accounts
  tag: 14

containerPort: 8080

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

env:
  POSTGRES_DB: accountsdb
  POSTGRES_USER: siya7
  POSTGRES_PORT: 5432
  POSTGRES_HOST: accounts-db

secret:
  name: accounts-postgres-secret
  passwordKey: password

rabbitmq:
  image: rabbitmq:management
  username: guest
  password: guest
  port: 5672
  managementPort: 15672
  pv:
    storage: 1Gi
    path: /mnt/data/rabbitmq


appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: true
postgres_enabled: true
rabbit_mq_enabled: true