version: "3.8"

services:
  accounts-db:
    image: postgres:14-bullseye
    container_name: accounts-db
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: accountsdb
      POSTGRES_USER: siya7
      POSTGRES_PASSWORD: Welcome231
    volumes:
      - ./pgdata/accounts-data-new:/var/lib/postgresql/data
    networks:
      - eazybank
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U siya7 -d accountsdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  loan-db:
    image: postgres:14-bullseye
    container_name: loan-db
    ports:
      - "5437:5432"
    environment:
      POSTGRES_DB: loansdb
      POSTGRES_USER: siya7
      POSTGRES_PASSWORD: Welcome123
    volumes:
      - ./pgdata/loans-data:/var/lib/postgresql/data
    networks:
      - eazybank
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U siya7 -d loansdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  cards-db:
    image: postgres:14-bullseye
    container_name: cards-db
    ports:
      - "5438:5432"
    environment:
      POSTGRES_DB: cardsdb
      POSTGRES_USER: siya7
      POSTGRES_PASSWORD: Welcome421
    volumes:
      - ./pgdata/cards-data-new:/var/lib/postgresql/data
    networks:
      - eazybank
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U siya7 -d cardsdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      timeout: 10s
      retries: 10
    networks:
      - eazybank

  configserver:
    image: siya7/configserver:1
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - eazybank
    volumes:
      - configserver-data:/configserver/data

  eurekaserver:
    image: siya7/eurekaserver:5
    container_name: eurekaserver
    ports:
      - "8070:8070"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
    networks:
      - eazybank
    volumes:
      - eurekaserver-data:/eurekaserver/data


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - eazybank
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  accounts:
    image: siya7/accounts:7
    container_name: accounts
    build:
      context: .
    ports:
      - "8084:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8084/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: jdbc:postgresql://accounts-db:5432/accountsdb
      SPRING_DATASOURCE_USERNAME: siya7
      SPRING_DATASOURCE_PASSWORD: Welcome231
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      accounts-db:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    networks:
      - eazybank

  loans:
    image: siya7/loans:6
    container_name: loans-ms
    build:
      context: .
    ports:
      - "8085:8085"
    healthcheck:
      test: "curl --fail --silent localhost:8085/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: jdbc:postgresql://loan-db:5432/loansdb
      SPRING_DATASOURCE_USERNAME: siya7
      SPRING_DATASOURCE_PASSWORD: Welcome123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      loan-db:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    networks:
      - eazybank

  cards:
    image: siya7/cards:7
    container_name: cards-ms
    build:
      context: .
    ports:
      - "8086:8086"
    healthcheck:
      test: "curl --fail --silent localhost:8086/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: jdbc:postgresql://cards-db:5432/cardsdb
      SPRING_DATASOURCE_USERNAME: siya7
      SPRING_DATASOURCE_PASSWORD: Welcome421
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      cards-db:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    networks:
      - eazybank

  gatewayserver:
    image: "siya7/gatewayserver:2"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    depends_on:
      loans:
        condition: service_healthy
      cards:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_DATA_REDIS_CONNECT-TIMEOUT: 2s
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 1s
    networks:
      - eazybank

networks:
  eazybank:
    driver: bridge

volumes:
  configserver-data:
  eurekaserver-data: