apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loans-postgres
  template:
    metadata:
      labels:
        app: loans-postgres
    spec:
      containers:
        - name: loans-postgres
          image: postgres:14
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.auth.existingSecret }}
                  key: {{ .Values.postgresql.auth.secretKeys.userPasswordKey }}
          ports:
            - containerPort: {{ .Values.postgresql.port | default 5432 }}