apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loans-postgres
  template:
    metadata:
      labels:
        app: loans-postgres
    spec:
      containers:
        - name: loans-postgres
          image: postgres:14
          env:
            - name: POSTGRES_DB
              value: {{ .Values.env.POSTGRES_DB }}
            - name: POSTGRES_USER
              value: {{ .Values.env.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.passwordKey }}
          ports:
            - containerPort: {{ .Values.env.POSTGRES_PORT | default 5432 }}