apiVersion: v1
kind: Service
metadata:
  name: accounts-db
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.env.POSTGRES_PORT }}
      targetPort: {{ .Values.env.POSTGRES_PORT }}
  type: ClusterIP
  selector:
    app: accounts-postgres