# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: loans-deployment
serviceName: loans
appLabel: loans
appName: loans

replicaCount: 1

image:
  repository: siya7/loans
  tag: 11

containerPort: 8085

service:
  type: ClusterIP
  port: 8085
  targetPort: 8085

env:
  POSTGRES_DB: loansdb
  POSTGRES_USER: siya7
  POSTGRES_PORT: 5432
  POSTGRES_HOST: loans-db

secret:
  name: loans-postgres-secret
  passwordKey: password

rabbitmq:
  image: rabbitmq:management
  username: guest
  password: guest
  port: 5672
  managementPort: 15672
  pv:
    storage: 1Gi
    path: /mnt/data/rabbitmq

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: true
postgres_enabled: true
rabbit_mq_enabled: true